<?php

namespace Database\Seeders;

use App\Models\Arsip;
use Illuminate\Database\Seeder;

class ArsipSeeder extends Seeder
{
    public function run(): void
    {
        $arsip = [
            [
                'id_user' => 7,
                'id_kategori' => 2,
                'kode' => 'REG-20260101-001',
                'nama' => 'Surat Keterangan Ahli Waris Alm. Sukarman',
                'deskripsi' => 'Dokumen penetapan ahli waris keluarga Almarhum Sukarman, warga RT 02 RW 01 Kelurahan Kebonsari Kulon',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => '2031-01-01',
                'status_retensi' => 'sementara',
                'status_validasi' => 'diterima',
                'pesan_penolakan' => null,
            ],
            [
                'id_user' => 7,
                'id_kategori' => 2,
                'kode' => 'REG-20260215-002',
                'nama' => 'Surat Keterangan Ahli Waris Almh. Siti Aminah',
                'deskripsi' => 'Surat keterangan hak waris bersama untuk pembagian hak tanah keluarga Almarhumah Siti Aminah di Kelurahan Tisnonegaran',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => null,
                'status_retensi' => 'permanen',
                'status_validasi' => 'diterima',
                'pesan_penolakan' => null,
            ],
            [
                'id_user' => 4,
                'id_kategori' => 3,
                'kode' => 'REG-20260320-003',
                'nama' => 'IMB Rumah Tinggal - Bp. Handoko',
                'deskripsi' => 'Izin Mendirikan Bangunan untuk rumah tinggal baru 1 lantai milik Handoko di Jl. Mastrip, Kelurahan Kanigaran',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => '2030-05-10',
                'status_retensi' => 'sementara',
                'status_validasi' => 'ditolak',
                'pesan_penolakan' => 'Dokumen persyaratan belum lengkap',
            ],
            [
                'id_user' => 5,
                'id_kategori' => 2,
                'kode' => 'REG-20260405-004',
                'nama' => 'Surat Keterangan Ahli Waris Alm. Bambang Wijaya',
                'deskripsi' => 'Berkas permohonan surat keterangan ahli waris dari keluarga Alm. Bambang Wijaya, warga Kelurahan Curahgrinting',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => '2032-12-31',
                'status_retensi' => 'sementara',
                'status_validasi' => 'pending',
                'pesan_penolakan' => null,
            ],
            [
                'id_user' => 6,
                'id_kategori' => 3,
                'kode' => 'REG-20260405-005',
                'nama' => 'IMB Ruko Dua Lantai - PT Maju Bersama',
                'deskripsi' => 'Penerbitan dokumen IMB untuk kompleks ruko komersial 2 lantai di kawasan perdagangan Jl. Cokroaminoto, Kelurahan Kanigaran',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => null,
                'status_retensi' => 'permanen',
                'status_validasi' => 'diterima',
                'pesan_penolakan' => null,
            ],
            [
                'id_user' => 2,
                'id_kategori' => 2,
                'kode' => 'REG-20260511-006',
                'nama' => 'Surat Keterangan Ahli Waris Alm. Supardi',
                'deskripsi' => 'Kelengkapan administrasi ahli waris Alm. Supardi guna keperluan pengurusan klaim jaminan pensiun di Kelurahan Sukoharjo',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => '2031-05-11',
                'status_retensi' => 'sementara',
                'status_validasi' => 'diterima',
                'pesan_penolakan' => null,
            ],
            [
                'id_user' => 3,
                'id_kategori' => 2,
                'kode' => 'REG-20260515-007',
                'nama' => 'Surat Keterangan Ahli Waris Almh. Sri Wahyuni',
                'deskripsi' => 'Surat keterangan hak waris properti dan mutasi hak perwalian dari Almarhumah Sri Wahyuni, Kelurahan Kebonsari Wetan',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => null,
                'status_retensi' => 'permanen',
                'status_validasi' => 'pending',
                'pesan_penolakan' => null,
            ],
            [
                'id_user' => 4,
                'id_kategori' => 2,
                'kode' => 'REG-20260518-008',
                'nama' => 'Surat Keterangan Ahli Waris Alm. Ahmad Fauzi',
                'deskripsi' => 'Pengajuan berkas surat keterangan ahli waris tunggal atas nama Ahmad Fauzi, berdomisili di Kelurahan Tisnonegaran',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => '2030-05-18',
                'status_retensi' => 'sementara',
                'status_validasi' => 'ditolak',
                'pesan_penolakan' => 'Tanda tangan kepala desa belum tersedia',
            ],
            [
                'id_user' => 5,
                'id_kategori' => 3,
                'kode' => 'REG-20260520-009',
                'nama' => 'IMB Gudang Logistik - CV Sumber Makmur',
                'deskripsi' => 'Permohonan izin mendirikan bangunan gudang penyimpanan logistik kering non-B3 di wilayah industri Kelurahan Sukoharjo',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => null,
                'status_retensi' => 'permanen',
                'status_validasi' => 'diterima',
                'pesan_penolakan' => null,
            ],
            [
                'id_user' => 6,
                'id_kategori' => 2,
                'kode' => 'REG-20260522-010',
                'nama' => 'Surat Keterangan Ahli Waris Alm. Djoko Susanto',
                'deskripsi' => 'Dokumen penetapan ahli waris sah keluarga besar Alm. Djoko Susanto guna penutupan rekening bank di Kelurahan Kebonsari Kulon',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => '2033-05-22',
                'status_retensi' => 'sementara',
                'status_validasi' => 'pending',
                'pesan_penolakan' => null,
            ],
            [
                'id_user' => 2,
                'id_kategori' => 2,
                'kode' => 'REG-20260525-011',
                'nama' => 'Surat Keterangan Ahli Waris Almh. Kartini',
                'deskripsi' => 'Surat keterangan hak waris mutlak dari Almarhumah Kartini untuk pengurusan peralihan sertifikat tanah di Kelurahan Kanigaran',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => '2029-05-25',
                'status_retensi' => 'sementara',
                'status_validasi' => 'diterima',
                'pesan_penolakan' => null,
            ],
            [
                'id_user' => 3,
                'id_kategori' => 3,
                'kode' => 'REG-20260527-012',
                'nama' => 'IMB Perluasan Toko Kelontong - Budi Utomo',
                'deskripsi' => 'Izin renovasi gedung dan perluasan area bangunan tempat usaha toko kelontong milik Budi Utomo di Kelurahan Curahgrinting',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => null,
                'status_retensi' => 'permanen',
                'status_validasi' => 'ditolak',
                'pesan_penolakan' => 'Dokumen site plan tidak dilampirkan',
            ],
            [
                'id_user' => 4,
                'id_kategori' => 2,
                'kode' => 'REG-20260601-013',
                'nama' => 'Surat Keterangan Ahli Waris Alm. Hendra Setiawan',
                'deskripsi' => 'Berkas arsip surat keterangan ahli waris Alm. Hendra Setiawan yang diajukan oleh pihak keluarga besar di Kelurahan Kebonsari Wetan',
                'file' => 'arsip/dokumen.pdf',
                'tanggal_retensi' => '2034-06-01',
                'status_retensi' => 'sementara',
                'status_validasi' => 'diterima',
                'pesan_penolakan' => null,
            ],
        ];

        foreach ($arsip as $item) {
            Arsip::create($item);
        }
    }
}
